name: Build and Deploy Release

on:
  workflow_dispatch:
  push:
    tags:        
      - 'v*'          
permissions:
  id-token: write

jobs:
  call-build:
    uses: conda-incubator/jupyterlab-conda-store/.github/workflows/build.yml@main

  deploy-build:
    runs-on: ubuntu-latest
    if: always() # Runs despite playwright tests failing
    needs: call-build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download extension package
      uses: actions/download-artifact@v3
      with:
        name: extension-artifacts
        path: dist/
      
    - name: Upload to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1        
